### ISSUE TITLE
push notification

### ISSUE THREAD

**Issue by Prolas** [SkySync-EPFL/skysync#213]
Function to send a notification
Select users to set the notification
Setup firebase / dependencies
Task is to read documentation and create a plan to implement it next sprint
Can be used for:
* flight confirmation
* assignment

**Comment by hacknstack** [comment]
Found ways to subscribe user to a topic, could be usefull for admin/pilot/crew separation but also for flight group notfications.
Methods discovered to show notifcation when app in on the background and foreground.
With method found notification should take 1-2 minutes to reach selected users, which is ok considering the use scenarios in skysync.
Code to send notification is on the server side which could be hard to debug and interact with.
