### ISSUE TITLE
db functions to filter for available equipment/user and for flights for user

### ISSUE THREAD

**Issue by Prolas** [SkySync-EPFL/skysync#219]
- add db functions to return equipment filtered for availability:
-> an equipment can be used only once per (date, timeslot). => getBasketsAvailableFor(date, timeslot): List(Basket)
- add db functions to return user filtered for availability:
-> a user can be assigned on a flight for a given (date, timeslot) only if he is available on that slot and not yet assigned to another balloon => getUserAvailableFor(date, timeslot): List(User)
- add functions to return flights filtered by user e.g. getFlightsForUser(User): List(Flights)

**Comment by RAFInery** [comment]
the last task is actually already implemented as `retrieveAssignedFlights` in the UserTable
