### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Prolas** [SkySync-EPFL/skysync#272]
Firestore offline mode
See if it is automatically handled

**Comment by hacknstack** [comment]
As seen on the firestore website (https://firebase.google.com/docs/firestore/manage-data/enable-offline#:~:text=When%20you%20initialize%20Cloud%20Firestore%2C%20you%20can%20enable,Firestore%27s%20cache%20isn%27t%20automatically%20cleared%20between%20sessions.%20) :
"Configure offline persistence
When you initialize Cloud Firestore, you can enable or disable offline persistence:

For Android and Apple platforms, offline persistence is enabled by default. To disable persistence, set the PersistenceEnabled option to false."
It's activated by default, after a thorough test (message,calendar and flight adding/modif/delete) it works fine.
